@extends('layouts.frontend.app')

@section('title', 'Terms')

@push('css')

	<!-- Template Main CSS File -->
	<link href="{{ asset('assets/css/front/style.css') }}" rel="stylesheet">


	<!-- Fonts -->
	<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

@endpush

@section('content')


  <div class="infinity-container">
		<div class="infinity-form-block">
			<button  type="button" class="text-center btn btn-primary justify-content-center col-md " data-bs-toggle="modal" data-bs-target="#myModal" >See Terms & Conditions</button>
	
            
            <!-- The Modal -->
			
					 <div class="modal" id="myModal">
					    <div class="modal-dialog modal-lg">
					      <div class="modal-content">
					  
					        <!-- Modal Header -->
					        <div class="modal-header">
					          <h4 class="modal-title text-center">CBfundraising Policies</h4>
					          <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
					        </div>
					  
					        <!-- Modal body -->
					        <div class="modal-body">
					          <h1 class="text-center">Terms & Conditions</h1>
							  <p class="justify-content">The following terms and conditions (the "Terms and Conditions") govern the use that you give this website and any of the content available by or to through this website, including any content derived from it (https://cbfundraising.site). CB fundraising has made the Website available to you. We may change the Terms and Conditions from time to time, at any moment without any notification, only publishing the changes on the Website. BY USING THE WEBSITE, YOU ACCEPT AND AGREE TO THESE TERMS AND CONDITIONS REGARDING YOUR USE OF THE WEBSITE. If you are not In accordance with these Terms and Conditions, you may not have access to it or use The Website in any other way.</p>
					      <p class="justify-content">Subject to these Terms of Service and any modifications made to them. Periodically ("Terms of Service"), CB fundraising provides to you, the Platform Cbfundraising. site through its website and related services (In conjunction with the CB fundraising Platform and including the new functions and services to charities, the CB fundraising platform through its site Web htpp: //cbfundraising.site and related services of both the CB Platform Fundraising (CBF) these services, in regards to the creation of accounts and the Processing of donations, they will be canceled in 30 days after the creation of the Event (together, the CBF Platform and related services are called hereinafter the "CBF Services for Charitable Organizations"). If you are an Organizer (as defined below), Beneficiary (as defined later) of an event (as defined below), Commenter or Donor (as defined below) (referred to herein as Jointly, the "User") from the United States, is entering into a contract with CB Fundraising. Inc. Mississippi 39564 USA the terms CB fundraising and other terms Similar will refer to the party with whom you are celebrating the contract.</p>
					      <p class="justify-content">Waiver of arbitration, jury trial, and collective action: except Otherwise described below in the dispute section, by using the CB fundraising services or the CBF services for charitable organizations (together, the “services”), you agree that disputes arising between us and you will be they will resolve through a binding and individual arbitration, and the waiver of your right to a jury trial or to participate in a collective action. Please review the dispute section carefully; by signing this agreement, you expressly acknowledge that you have read and understood all the terms of this agreement.</p>
					      <p class="justify-content">We reserve the right, at our sole discretion, to change or modify these Terms of Service at any time and without prior notice. That if so, we will post the revised Terms of Service on this page and indicate the date these terms were last revised. The continued use of the Services that you make after the date of entry. The effective date of these changes implies your acceptance of the new Terms of Service. To the extent permitted by law, the English version of these Terms of Use Service will be binding and any other translation will only have the purpose make it easy to read. If you do not want to accept these new terms of Service, you can stop using the Services. In addition, when using the Services, and unless you are in the Space European Economic, the United Kingdom and Switzerland (“Europe”) will be subject to additional applicable including but not limited to the privacy policy. All these terms are incorporate by reference to these Terms of Service (provided when, however, these Terms of Service applied as a prevalence in case of conflict). We will resolve such disputes at our entire discretion, and all our decision and all our decisions will be final.</p>
					        </div>

							<div class="modal-body">
								<h1 class="text-center">ACCESS AND USE OF THE SERVICES</h1>
								<p class="justify-content" ><u>Property Rights:</u> Between you and CB fundraising, CB fundraising owns sole and exclusive, of all rights, title, and interests in and of the Website, of all content (including, for example, audio, photos, illustrations, graphics, other visual media, videos, copies, texts, software, titles, Shock wave, etc.), codes, data and materials of the same. The appearance and the environment, the design and organization of the Website, and the compilation of contents, codes, data, and materials on the Website, including but not limited to, any copyright, trademark rights, patent rights, database rights, moral rights, sui generis rights and others intellectual properties and patrimonial rights thereof. Your use of the Website does not grant ownership of any of the content, codes, data, or materials to those you can access on or through the Site.</p>
					      <p class="justify-content" ><u>Limited License:</u> You can access and view the content of the website from your computer or any other device unless otherwise indicated in these Terms and Conditions on the website, make copies or individual impressions of the content of the website for your personal or internal use only. The use of the Website and the services offered are for your personal, non-commercial use only.</p>
					      <p class="justify-content" ><u>Description of CB fundraising Services:</u> CB fundraising Services are offered through a platform to allow a natural or legal person, or a non-profit organization (“Event Administrator”) to post an event ("Event") on the Cb fundraising. Site Platform to accept donations (Donations) from donors (“Donors”) on behalf of the beneficiary of the event ("Beneficiary") The Organizer (Event Administrator) and/or the event will not offer goods or services in exchange for Donations. CB fundraising will need to approve each event before it is published.  We may cancel the event if you do not comply with our terms. Payment provider: CB fundraising is not a payment provider, nor is it holding funds. On the contrary, CB fundraising uses external partners to process Donations to an event ("Payment Provider"). You accept and acknowledge that the participation of Payment Providers is essential for the Services and that We exchange information with Payment Providers to facilitate the provision of services.</p>
					      <p class="justify-content" >At CB fundraising we are a platform; we are not a Financial Intermediary, a Financial Institution, a Creditor, or a Charitable Organization. Services are only administrative platforms. CB fundraising facilitates the event to the Organizers and allows Donors to donate to this event. CB fundraising is not a financial intermediary, agent, financial institution, creditor, or a financial organization all the information and content provided by CB fundraising in relation to the services is for informational purposes only, and CB fundraising does not guarantee the accuracy, completeness, availability, or veracity of said information or content. No content is intended to provide financial, legal advice, tax, or other professional advice. Before making any decision event-related, Charitable Organizations (defined below) Donations, Donors, or any information or content related to the Services, you should consult your financial, legal, tax, or another professional adviser, as appropriate. You acknowledge that all information and content to which Access through the Services is at your own risk. CB fundraising has no control over the conduct or any information provided by a User and, hereby, you renounce to exercise any liability action in this sense to the extent that the applicable law allows. We do not guarantee that an event will get a certain amount of Donations or not even receive a Donation. We do not endorse any event, User, or cause and we do not offer any warranty, express or implied, that the information provided through the Services is accurate. We exclude assuming any type of responsibility or obligation for the result or success of an event. You, as the Donor, must make the final decision regarding the value and convenience of donating to.</p>
					      <p class="justify-content" ><u>No application:</u>The CB fundraising platform is to help Organizers (event administrators) to raise money. CB fundraising simply provides the technology to allow Organizers to (event managers) of events to connect with Donors. The existence of the Services is not a request for Donations by CB fundraising and CB fundraising does not participate in any fundraising activity or consultation on the request for Donations by the public, on behalf of any individual, entity, or organization. By using the Services, you understand and agree that CB fundraising will not be responsible for the use of your Donations or the amount of funds collected for the User or the event.</p>
					      <p class="justify-content" ><u>Donors:</u>All Donations are at your own risk. When you make a Donation through the CB fundraising Platform, it is your responsibility to understand how the money will be use. CB fundraising is not responsible for any offer, promise, reward or promotion made or offered by Users or events; bliss conduct violates these Terms of Service. We do not verify, nor do can we verify, the information provided by Users or events, nor do we declare or guarantee that Donations will be used in accordance with the purpose of recruitment of funds prescribed by a User or an event or in accordance with the laws applicable. Notwithstanding the foregoing, we take very seriously the possible fraudulent activities and misuse of the funds collected. Can get more information about this in our terms and services. If you have reason to believe that a User or event does not collect or use the funds for its indicated purpose, use the "Report" button in the Campaign to alert our team of this possible problem and we will investigate it.</p>
					      <p class="justify-content" >Donors are not allow to impose restrictions on the use of Donations by a non-profit organization established as such in accordance with the applicable constitution laws ("Charity Organization"). In the extent to which a Donation is made in response to an appeal for a particular program of an event or a Charity Organization.  In the extent to which a Donor intends to direct the use of Donations by a Charity Organization, such instructions shall only constitute non-binding recommendations, and the Charity will have full discretion to determine how all Donations will be used.</p>
					      <p class="justify-content" >CB fundraising does not make any representation as to whether all or one part of their Donations, including, if any, Commissions for the transaction, are tax-deductible or meet the requirements for getting tax breaks. CB fundraising will have no responsibility for any claim by any federal authority, state, provincial, territorial, local, or any other tax authority regarding the description. You make in any statement of taxes applicable to any Donation made by you, of any User, or any charity organization or event. You should consult your tax advisor regarding the amount of your Donation that is tax-deductible fiscally or that meets the requirements for tax recognition, having taken into account (among other things) the tax situation of the recipient of any Donation in any relevant jurisdiction.</p>
					      <p class="justify-content" >Unless Donor objects to such disclosure, Donor acknowledges and agrees that in accordance with the Privacy Policy.  Certain Donor's personal information will be shared with the Charity who receives a Donation from the Donor (including, but not limited to, as part of a Donor List, as set out below) and what may be used by the Charity Organization to issue official receipts for Donations (or equivalent documentation). In addition, in accordance with the Policy of Privacy of the Charity Organization. CB fundraising is not responsible for any moral or legal use made by a Charity Organization or event of any information from the donor.</p>
					      <p class="justify-content" ><u>Organizer or administrator of the event:</u>You, as Organizer, declare, guarantee, and promise that all information you provide in connection with a Recipient event is accurate and complete, and is not likely to mislead reasonably attentive users. All Donations contributed to your event will be used only as described in the materials you post or provide on our platform or otherwise. If you withdraw, Donations those reasonably attentive donors consider that they were raised in the representation of a person other than you (the Beneficiary), all Donations will be given to the Recipient or will be spent on their behalf. You are not infringing the rights of others. You will comply with all laws and obligations corresponding to and applicable financial reporting, including but not limited to laws and regulations related to enrollment, tax information, political contributions, and asset disclosure of your event. The extent to which you share personal data of third parties with us with any purpose, including names, email addresses, and numbers telephone numbers of your contacts.  You have the authority (including required permits), as required by applicable law, to provide us with these personal data and allow us to use it for the purposes under which you provided them. You will not offer goods or services to change of Donations. You authorize CB fundraising to reserve the right to provide information about your event to Donors, Beneficiaries of your event, and police authorities and collaborate in any investigation.</p>
					      <p class="justify-content" >If you use the Services as an agent of a Charity Organization to collect funds for said Charitable Organization, you represent and guarantee that: a) You are a representative of the Charity Organization, and as such, is authorized to collect funds for the Charity Organization and forcing the Charity Organization to be subject to these Terms of Service; b) You are raising funds for a Charity Organization, with a lawful cause or activity under all laws and applicable federal, state, provincial, territorial and local regulations. c) All donated funds will be use solely for the purposes that you have declared and concerning your event and under no circumstances may you use the funds for another purpose. d) Your Charitable Organization has and will maintain its tax-exempt status under applicable law (for example, the US Internal Revenue Code or the Income Tax Law from Canada). e) If your Charity is in the United States, it is register in the Guide Star database or the database of exempt organizations IRS (United States Revenue Agency) taxes or, in Canada, it appears on the database of registered charities of the Tax Agency of Canada (Canada Revenue).</p>
					      <p class="justify-content" ><u>Your registration obligations:</u>You may need to register with CB fundraising to access and use certain features of the Services. If you choose to register for the services, you agree to provide and maintain truthful, accurate, up-to-date, and complete information about you and your event as requested in the registration form services. Event Management Organizers must register with their identity (or the identities of the authorized representatives of the Charities), including your name, address, and any images that intend to represent the Organizer or Beneficiary of the event. You undertake to keep the registration information up to date. These Terms of Service, including our Privacy Policy, govern registration data and other information about you. If you are under 13 years old (16 in Europe), you are not authorized to use the Services, regardless of whether you register or No. Also, if you are a minor in your jurisdiction (usually 18 or 19 years of age).  You can use the Services, regardless of whether you register or not, only with the approval of your parent or guardian. Certain aspects of our Services They may also require you to register with third-party service providers with those that CB fundraising has entered into contracts that accepts their terms (for For example, Payment Providers) to benefit from their services. Yes, CB fundraising or one of our Payment Providers discovers at any time that the information provided about you or the purpose of your event is incorrect or violates any of these Terms of Service or the terms of service of such providers, your access to the Services may be suspended or terminated with immediate effect and the relevant authorities may apply fines, that in all these cases will be paid by you. You acknowledge and agree that the Use of Payment Providers is an integral part of the Services we exchange information with these third parties to facilitate the provision of Services as provided in our Privacy Policy.</p>
					       <p class="justify-content" ><u>Taxes:</u>It is your sole responsibility to determine what taxes if any, they will be applied to the Donations you receive by the Services. Is Your sole responsibility to assess, collect, declare or remit taxes Relevant, if any, to the authority.</p>
					       <p class="justify-content" ><u>Member account, password and security:</u>You are responsible for preserving the confidentiality of your password and account, if any, and fully responsible of each of the activities carried out with them. You agree to (a) immediately notify CB fundraising of any unauthorized use of your Password or account, or any other breach of security, (b) logout in your account at the end of each session when you access the Services. CB fundraising no Accepts no legal responsibility for loss or damage arising from the breach on your part of the provisions of this section.</p>
					       <p class="justify-content" ><u>Modifications of the Services:</u>CB fundraising reserves the right to modify, Suspend or discontinue, temporarily or permanently, the Services (or any part of them) at any time and for any reason, with or without prior notice, and without assuming any responsibility to you or any third party for claims, damages, costs or losses resulting therefrom.</p>
							  </div>


							  <div class="modal-body">
								<h1 class="text-center">Content made public by the User in a manifest way</h1>
					      <p class="justify-content" ><u>Public content:</u>Public presentation of information and Donations, Part of Your activity on and through the Services is public as is the content that publicly exhibits on the CB fundraising Platform.  (which includes descriptions, texts, music, sound, information, data, software, graphics, comments, photos, videos, images, trademarks, logos, brands or other materials that you upload or post through the Services or that Share with other Users or recipients).  ("User Content"). In addition, the information of the user profile, including their name and surname, public email address, organization, personal bio, and other information that you enter concerning your User profile, you can be shown to other users to facilitate the interaction of Users within of the Services. For example, as Organizer, you may post personal data about you, such as information about a recent stay at the hospital, which it will be consider confidential information. In addition, to the view of everyone, even in search engines (like Google and Yahoo). To keep your details in the public press the share button my donation, remember that if you decide to provide information using certain public functions of the Services, such information is govern due to the privacy settings of those specific features and the itself is available to the public. The people who read that information may use or disclose it to other people or entities without our knowledge of yours and search engines will be able to index that information. Therefore, we urge you to think carefully about include any specific information that you may consider private in the content that you create or in the information that you send through the Services. See our privacy policy for information on how we may collect, use and retain certain information about you and your use of the Services.</p>
					      <p class="justify-content" ><u>Other information:</u>Please note that the Content of the User and other information, requested or unsolicited, that you provide to Cb fundraising is publicly accessible, like the information you post in forums, comment sections, or in responses to surveys that we can send you. We also collect information via customer service communications when you communicate for new products, modifications of existing products, and others unsolicited submissions, questions, comments, suggestions, ideas, opinions, or other information about the Services. (Together with the information public access, "Other Information") By sending us Other Information, a) You agree that we have no obligation of confidentiality, express or implied, with respect to the Other Information. b) You acknowledge that it is we may have something similar to the Other Information already under consideration or Developing; c) You agree that Cb fundraising will have the right to use and unlimited dissemination of the Other Information for any commercial or otherwise, without recognition or compensation to you; d) You declare and guarantees that you have all the necessary rights to send the other information; e) to the extent necessary, you hereby grant to CB fundraising a perpetual, royalty-free, fully paid right, irrevocable, worldwide, non-exclusive and fully transferable and sub licensable, (to across multiple levels) and a license to use, reproduce, perform, display, distribute, adapt, modify, reformat, create works derived and exploit in any other way, commercially or not commercially. Any Other Information, and to sublicense the rights previous; and f) you irrevocably resign, and cause the resignation, of any claim and the manifestation of the moral rights contained in the Other Information in front of CB fundraising and its Users. This section of Other Information will remain in effect after the termination of your account or the Services.</p>
					      <p class="justify-content" >You acknowledge and agree that CB fundraising may retain the Information, as well as the User Content, and may disclose other Information or User Content.  If required by law or if you believe in good faith, that said retention or disclosure is reasonably necessary to a) comply with legal requirements, applicable laws or government requests; b) enforce these Terms of Service; c) respond to claims regarding that any User Content violates the rights of third parties; or d) protect rights, property or personal safety of CB fundraising, its Users or the public.</p>
					      <p class="justify-content" ><u>Promotions on the CB fundraising Platform:</u>You are not allowed to offer any contest, competition, reward, gift, raffle, raffle, or similar activity in the Services or through these.</p>
					      <p class="justify-content" ><u>Sales prohibited on the CB fundraising platform:</u>You are not allow to offer any Good or service in exchange for a Donation on the CB fundraising platform.</p>
					      <p class="justify-content" ><u>Data Retention:</u>You acknowledge that CB fundraising has no obligation to keep the data related to any account or event. You acknowledge that CB fundraising reserves the right to delete data or cancel account or end events at any time and for any reason, with or without prior notice, and without any liability to you or any third party in concept resulting claims, damages, costs, or losses. The above does not apply to events or accounts initiated by Charitable Organizations on the CB Platform fundraising.  In which CB fundraising will provide reasonable notice when it is possible.</p>
					      <p class="justify-content" ><u>Payment providers:</u>CB fundraising uses Payment Providers to process Donations for its event and subsequently deliver them to you. To withdraw funds from an event, an Organizer or, if not the same, the Beneficiary (jointly, the “Entity responsible for the withdrawal”) will have to provide the information of the Provider of Payments on the bank account information (Withdrawal Account). You as the Entity in charge of the withdrawal declare and guarantee the Payment Provider, CB fundraising that such information is true and that you authorized to use the corresponding Retirement Account. By establishing an event or accepting the role of Beneficiary of an event, the Entity.</p>
					      <p class="justify-content" >The person in charge of the withdrawal accepts the treatment, use, transfer, or disclosure of data by Payment Providers under these Terms of Services and each one of the applicable terms established by the applicable Payment Providers. These terms and conditions may be updated any changes will take effect immediately. Every time you perform a payment make sure you are aware of the current terms we appreciate you do not use this online service if you do not agree and do not accept the terms and conditions.</p>
							  </div>

							  
					  
					        <!-- Modal footer -->
					        <div class="modal-footer">
					          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
					        </div>
					  
					      </div>
					    </div>
					  </div>
  

				
				</div>
			</div>
		</div>
	</div>




@stop

@push('js')
	<!-- Template Main JS File -->
	<script src="assets/js/main.js"></script>
@endpush